## VIF

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("salaries for VIF.csv")

In [4]:
data.head()

   Years of Experience  Education Level  Age  Location Factor  Salary
0                   29                1   49                7  124204
1                   27                3   45                4  125948
2                   20                4   41                8  116078
3                   14                4   37                5  106486
4                   20                3   42                7  113297

In [5]:
data = data.drop("Salary",axis = 1)

In [6]:
data.shape[1]

4

In [7]:
data.head()

   Years of Experience  Education Level  Age  Location Factor
0                   29                1   49                7
1                   27                3   45                4
2                   20                4   41                8
3                   14                4   37                5
4                   20                3   42                7

In [10]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [11]:
def calculateVif(data):
    vif = []
    output = pd.DataFrame()
    output["Attributes"] = data.columns
    for i in range(0,data.shape[1]):
        vif.append(variance_inflation_factor(data,i))
    output["vif"] = vif
    return output

In [13]:
calculateVif(data)

            Attributes        vif
0  Years of Experience  22.342087
1      Education Level   5.472969
2                  Age  42.201149
3      Location Factor   4.289467

In [14]:
data = data.drop("Age",axis = 1)

In [15]:
calculateVif(data)

            Attributes       vif
0  Years of Experience  3.198601
1      Education Level  3.509425
2      Location Factor  3.231181