In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_csv("cars93.csv")
data.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [3]:
data["Type"].unique()

array(['Small', 'Midsize', 'Compact', 'Large', 'Sporty', 'Van'],
      dtype=object)

In [4]:
le = LabelEncoder()

In [5]:
data["Type"] = le.fit_transform(data["Type"])

In [6]:
data.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,3,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,2,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,0,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,2,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,2,30.0,22,Driver only,208,4,27.0,13.0

In [7]:
data = pd.read_csv("cars93.csv")
data.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [8]:
from sklearn.preprocessing import OrdinalEncoder
ord = OrdinalEncoder(categories=[["Compact","Sporty","Small","Midsize","Van","Large"]])
data["Type"] = ord.fit_transform(data[["Type"]]).astype("int")

In [9]:
data.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,2,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,3,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,0,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,3,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,3,30.0,22,Driver only,208,4,27.0,13.0

## OneHotEncoder

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
data = pd.DataFrame({"Type":["Butterscpoth","Vanilla","Chocolate","Kaju","Butterscpoth","Kaju","Butterscpoth","Vanilla","Kaju","Vanilla"],
                     "Size":["Small","Medium","Large","Small","Large","Medium","Small","Large","Medium","Medium"],
                     "Qnt":[2,3,4,5,1,2,3,5,3,2]
    
})

In [15]:
data.head()

           Type    Size  Qnt
0  Butterscpoth   Small    2
1       Vanilla  Medium    3
2     Chocolate   Large    4
3          Kaju   Small    5
4  Butterscpoth   Large    1

In [17]:
ohe = OneHotEncoder()
result = ohe.fit_transform(data[["Type"]]).toarray()

In [18]:
result

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
result = pd.DataFrame(result,columns = ["Butterscpoth","Vanilla","Chocolate","Kaju"])
result

   Butterscpoth  Vanilla  Chocolate  Kaju
0           1.0      0.0        0.0   0.0
1           0.0      0.0        0.0   1.0
2           0.0      1.0        0.0   0.0
3           0.0      0.0        1.0   0.0
4           1.0      0.0        0.0   0.0
5           0.0      0.0        1.0   0.0
6           1.0      0.0        0.0   0.0
7           0.0      0.0        0.0   1.0
8           0.0      0.0        1.0   0.0
9           0.0      0.0        0.0   1.0

In [22]:
data1 = pd.concat([data,result],axis = 1)
data1

           Type    Size  Qnt  Butterscpoth  Vanilla  Chocolate  Kaju
0  Butterscpoth   Small    2           1.0      0.0        0.0   0.0
1       Vanilla  Medium    3           0.0      0.0        0.0   1.0
2     Chocolate   Large    4           0.0      1.0        0.0   0.0
3          Kaju   Small    5           0.0      0.0        1.0   0.0
4  Butterscpoth   Large    1           1.0      0.0        0.0   0.0
5          Kaju  Medium    2           0.0      0.0        1.0   0.0
6  Butterscpoth   Small    3           1.0      0.0        0.0   0.0
7       Vanilla   Large    5           0.0      0.0        0.0   1.0
8          Kaju  Medium    3           0.0      0.0        1.0   0.0
9       Vanilla  Medium    2           0.0      0.0        0.0   1.0

In [23]:
data1.drop("Type",axis = 1,inplace = True)
data1

     Size  Qnt  Butterscpoth  Vanilla  Chocolate  Kaju
0   Small    2           1.0      0.0        0.0   0.0
1  Medium    3           0.0      0.0        0.0   1.0
2   Large    4           0.0      1.0        0.0   0.0
3   Small    5           0.0      0.0        1.0   0.0
4   Large    1           1.0      0.0        0.0   0.0
5  Medium    2           0.0      0.0        1.0   0.0
6   Small    3           1.0      0.0        0.0   0.0
7   Large    5           0.0      0.0        0.0   1.0
8  Medium    3           0.0      0.0        1.0   0.0
9  Medium    2           0.0      0.0        0.0   1.0

In [24]:
data.head()

           Type    Size  Qnt
0  Butterscpoth   Small    2
1       Vanilla  Medium    3
2     Chocolate   Large    4
3          Kaju   Small    5
4  Butterscpoth   Large    1

In [27]:
data1 = pd.get_dummies(data,columns = ["Type"],dtype = "int",drop_first=True)
data1

     Size  Qnt  Type_Chocolate  Type_Kaju  Type_Vanilla
0   Small    2               0          0             0
1  Medium    3               0          0             1
2   Large    4               1          0             0
3   Small    5               0          1             0
4   Large    1               0          0             0
5  Medium    2               0          1             0
6   Small    3               0          0             0
7   Large    5               0          0             1
8  Medium    3               0          1             0
9  Medium    2               0          0             1

In [29]:
data2 = pd.get_dummies(data,columns = ["Type","Size"],dtype = "int")
data2

,Qnt,Type_Butterscpoth,Type_Chocolate,Type_Kaju,Type_Vanilla,Size_Large,Size_Medium,Size_Small
0,2,1,0,0,0,0,0,1
1,3,0,0,0,1,0,1,0
2,4,0,1,0,0,1,0,0
3,5,0,0,1,0,0,0,1
4,1,1,0,0,0,1,0,0
5,2,0,0,1,0,0,1,0
6,3,1,0,0,0,0,0,1
7,5,0,0,0,1,1,0,0
8,3,0,0,1,0,0,1,0
9,2,0,0,0,1,0,1,0