In [51]:
import pandas as pd
import numpy as np

In [52]:
data = pd.read_csv("Iris.csv")

In [53]:
data.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

## LabelEncoder

In [26]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv("iris.csv")

le = LabelEncoder()
data["Species"] = le.fit_transform(data["Species"])

In [27]:
data

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  Species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [30]:
from sklearn.preprocessing import OneHotEncoder

In [31]:
le1 = OneHotEncoder()

In [43]:
result = data["Species"] = le1.fit_transform(data[["Species"]]).toarray()

In [44]:
data.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  Species
0           5.1          3.5           1.4          0.2      1.0
1           4.9          3.0           1.4          0.2      1.0
2           4.7          3.2           1.3          0.2      1.0
3           4.6          3.1           1.5          0.2      1.0
4           5.0          3.6           1.4          0.2      1.0

## OneHotEncoding

In [55]:
data1 = pd.get_dummies(data, columns=["Species"], dtype=int, drop_first=True)

In [56]:
data1.head()

,Sepal_Length,Sepal_Width,Petal_Length,Petal_Width,Species_Versicolor,Species_Virginica
0,5.1,3.5,1.4,0.2,0,0
1,4.9,3.0,1.4,0.2,0,0
2,4.7,3.2,1.3,0.2,0,0
3,4.6,3.1,1.5,0.2,0,0
4,5.0,3.6,1.4,0.2,0,0